---
language: node_js
node_js:
  - 11
dist: trusty
sudo: false
install: |

  git clone https://github.com/devsnek/engine262.git;
  cd engine262 && npm install && npm run build && npm link;
  cd $TRAVIS_BUILD_DIR;

  npm install jsvu;

  export PATH="${HOME}/.jsvu:${PATH}";
  echo $PATH;

  ./node_modules/.bin/jsvu --os=linux64 --engines=all;

  npm install --ignore-scripts && npm link;

  ./node_modules/.bin/eshost --add "chakra" ch ~/.jsvu/chakra;
  ./node_modules/.bin/eshost --add "engine262" engine262 `which engine262`;
  ./node_modules/.bin/eshost --add "javascriptcore" jsc ~/.jsvu/javascriptcore;
  ./node_modules/.bin/eshost --add "spidermonkey" jsshell ~/.jsvu/spidermonkey;
  ./node_modules/.bin/eshost --add "v8" d8 ~/.jsvu/v8;
  ./node_modules/.bin/eshost --add "xs" xs ~/.jsvu/xs;

script:
  - which chakra
  - which engine262
  - which javascriptcore
  - which spidermonkey
  - which v8
  - which xs

