version: "{build}"

clone_depth: 1

environment:
  matrix:
    # - nodejs_version: 10
    - nodejs_version: 11

platform:
  - x64
  # - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: .\scripts\prepare-engine-env.ps1
  - cmd: eshost --list

build: off

test_script:
  - cmd: eshost -e "1 + 1"

matrix:
  fast_finish: true
