version: "{build}"

clone_depth: 1

environment:
  matrix:
    - nodejs_version:
      - 10
      - 12


platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: .\scripts\prepare-engine-env.ps1
  # - cmd: .\scripts\prepare-engine-env.cmd

build: off

test_script:
  # - ps: eshost -e "1 + 1"
  # - eshost -e "1 + 1"
  - cmd: eshost --list
  - cmd: eshost -e "1 + 1"

matrix:
  fast_finish: true
